name: Validate PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run validator unit tests
        run: ./scripts/check-pr-title.test.sh
      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: ./scripts/check-pr-title.sh "$PR_TITLE"
